#libdefine BDEATH_MAXMARKEDSECTORS      256

#libdefine BMARK_MAXDEATHMARKS      128

#libdefine BRETURN_MAXPOINTS        128

#libdefine BSWITCH_MAXSWITCHES      128
#libdefine BSWITCH_CHECKDIST        320.0