// This file is automatically generated when building the PK3 file. Don't edit
//  it manually - look in precompile.py instead.

#define VERSION_MAJOR   0
#define VERSION_MINOR   6
#define VERSION_BUGFIX  0

#define VERSION_STRING       "0.6.0"
#define VERSION_COMMIT       "77da089b"
#define VERSION_COMMIT_LONG  "77da089bb5fd0142991113ffb3fcd7324e396f8e"
